import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "@/components/Provider";
import RecoilRootComponent from "@/components/RecoilRootComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Instagram Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <RecoilRootComponent>
        <Provider>
          <body className={inter.className}>{children}</body>
        </Provider>
      </RecoilRootComponent>
    </html>
  );
}
